Automation tests
VladFedash/TechStack-Selenium-Project pull request #1
Opened 2021-01-11 13:31 UTC by VladFedash

2021-01-12 16:00 UTC, OleksandrMishchenkoGit requested changes

2021-01-12 16:00 UTC, OleksandrMishchenkoGit commented on src/test/java/pages/HomePage.java
> +    @FindBy(xpath = "//span[contains(@class, \"button-counter\")]")
use '' instead of Escaping ""

2021-01-12 16:00 UTC, OleksandrMishchenkoGit commented on src/test/java/pages/HomePage.java
> +    @FindBy(xpath = "//span[contains(@class, \"button-counter\")]")
the same xpath works for wishlist counter

2021-01-12 16:00 UTC, OleksandrMishchenkoGit commented on src/test/java/pages/SearchResultsPage.java
> +    @FindBy(xpath = "(//button[contains(@class, \"buy-button\")])[1]")
use '' instead of Escaping ""

2021-01-12 16:00 UTC, OleksandrMishchenkoGit commented on src/test/java/pages/SearchResultsPage.java
> +    @FindBy(xpath = "//button[contains(@class, \"buy-button\")]")
use '' instead of Escaping ""

2021-01-12 16:00 UTC, OleksandrMishchenkoGit commented on src/test/java/pages/HomePage.java
> +    private WebElement searchField;
You can make all your WebElements public to avoid using unnecessary getters

2021-01-12 16:00 UTC, OleksandrMishchenkoGit commented on src/test/java/pages/HomePage.java
> +    }
You can make these common methods such as "click, input, ex...." parametrized. 
```
    public void clickButton(WebElement button) {
        waitForElementToBeDisplayed(button);
        button.click();
    }
```

2021-01-12 16:00 UTC, OleksandrMishchenkoGit commented on src/test/java/pages/HomePage.java
> +        return Integer.parseInt(totalProductPriceInCart.getText().replaceAll("[^0-9]", ""));
Add some wait here before action

2021-01-12 16:00 UTC, OleksandrMishchenkoGit commented on src/test/java/pages/HomePage.java
> +
remove spaces

2021-01-12 16:00 UTC, OleksandrMishchenkoGit commented on src/test/java/pages/BasePage.java
> +
remove spaces

2021-01-12 16:00 UTC, OleksandrMishchenkoGit commented on src/test/java/pages/SearchResultsPage.java
> +    public void clickAddProductInCartButton() {
rename method or modify. Here you will add all visible products to the Cart

2021-01-12 16:00 UTC, OleksandrMishchenkoGit commented on src/test/java/tests/BaseTest.java
> +    public void plug(){}
?

2021-01-12 16:00 UTC, OleksandrMishchenkoGit commented on src/test/java/tests/BaseTest.java
> +    }
if needed, you can create instances of pages directly in test

2021-01-12 16:00 UTC, OleksandrMishchenkoGit commented on src/test/java/tests/SearchResultTests.java
> +
remove spaces

2021-01-12 16:00 UTC, OleksandrMishchenkoGit commented on src/test/java/tests/SearchResultTests.java
> +
remove spaces

2021-01-12 16:00 UTC, OleksandrMishchenkoGit commented on src/test/java/tests/SortingTests.java
> +                    <= Integer.parseInt(getNotebooksPage().getProductPriceList().get(i + 1).getText().replace(" ", "")));
Better to move all prices into one List. Then create a copy of this List => Sort by asc/desc. Compare these two lists, they should be equal

2021-01-12 16:00 UTC, OleksandrMishchenkoGit commented on src/test/java/tests/SortingTests.java
> +                    >= Integer.parseInt(getNotebooksPage().getProductPriceList().get(i + 1).getText().replace(" ", "")));
Better to move all prices into one List. Then create a copy of this List => Sort by asc/desc. Compare these two lists, they should be equal

2021-01-12 16:00 UTC, OleksandrMishchenkoGit commented on src/test/java/tests/SortingTests.java
> +            assertTrue(element.getText().replaceAll("Н", "H").replaceAll("Р", "P").contains(CHOSEN_NOTEBOOK_FIRM));
???

2021-01-13 07:38 UTC, VladFedash commented on src/test/java/pages/HomePage.java
> +    @FindBy(xpath = "//span[contains(@class, \"button-counter\")]")
Changed

2021-01-13 07:41 UTC, VladFedash commented on src/test/java/pages/SearchResultsPage.java
> +    @FindBy(xpath = "(//button[contains(@class, \"buy-button\")])[1]")
Changed

2021-01-13 07:41 UTC, VladFedash commented on src/test/java/pages/SearchResultsPage.java
> +    @FindBy(xpath = "//button[contains(@class, \"buy-button\")]")
Changed

2021-01-13 07:42 UTC, VladFedash commented on src/test/java/pages/HomePage.java
> +    private WebElement searchField;
Changed

2021-01-13 09:46 UTC, VladFedash commented on src/test/java/pages/HomePage.java
> +    }
Changed

2021-01-13 09:47 UTC, VladFedash commented on src/test/java/tests/SearchResultTests.java
> +
Changed

2021-01-13 09:47 UTC, VladFedash commented on src/test/java/tests/SearchResultTests.java
> +
Changed

2021-01-13 09:47 UTC, VladFedash commented on src/test/java/tests/SortingTests.java
> +            assertTrue(element.getText().replaceAll("Н", "H").replaceAll("Р", "P").contains(CHOSEN_NOTEBOOK_FIRM));
Changed

2021-01-13 13:38 UTC, VladFedash commented on src/test/java/tests/SortingTests.java
> +                    >= Integer.parseInt(getNotebooksPage().getProductPriceList().get(i + 1).getText().replace(" ", "")));
Changed

2021-01-13 13:38 UTC, VladFedash commented on src/test/java/tests/SortingTests.java
> +                    <= Integer.parseInt(getNotebooksPage().getProductPriceList().get(i + 1).getText().replace(" ", "")));
Changed

2021-01-13 13:39 UTC, VladFedash commented on src/test/java/pages/HomePage.java
> +        return Integer.parseInt(totalProductPriceInCart.getText().replaceAll("[^0-9]", ""));
Changed

2021-01-13 13:39 UTC, VladFedash commented on src/test/java/pages/HomePage.java
> +
Changed

2021-01-13 13:39 UTC, VladFedash commented on src/test/java/pages/BasePage.java
> +
Changed

2021-01-13 13:42 UTC, VladFedash commented on src/test/java/pages/SearchResultsPage.java
> +    public void clickAddProductInCartButton() {
Changed

2021-01-13 13:44 UTC, VladFedash commented on src/test/java/tests/BaseTest.java
> +    public void plug(){}
Idea sent me a warning, that this class should contain some test and I created plug(заглушка). Deleted this Test.

2021-01-14 09:52 UTC, OleksandrMishchenkoGit requested changes

2021-01-14 09:52 UTC, OleksandrMishchenkoGit commented on src/test/java/tests/ActionWithCartTests.java
> +            basePage.clickButton(searchResultsPage.closeAdButton);
make it a separate method

2021-01-14 10:42 UTC, OleksandrMishchenkoGit approved these changes

2021-01-14 11:16 UTC, merged