Fifth commit
VladFedash/TechStack-Selenium-Project pull request #4
Opened 2021-01-22 17:54 UTC by VladFedash

2021-01-25 10:17 UTC, OleksandrMishchenkoGit requested changes

2021-01-25 10:17 UTC, OleksandrMishchenkoGit commented on src/test/java/helpers/BaseOperations.java
> +        waitForElementVisibilityShort(driver.findElement(by));
you can move WaitTime in enum and add waitTIme parameter to all your wait methods

2021-01-25 10:17 UTC, OleksandrMishchenkoGit commented on src/test/java/helpers/WaitUtils.java
> +    public void waitForUrl(long timeout, String str) {
remove this method. not really a usable thing

2021-01-25 10:17 UTC, OleksandrMishchenkoGit commented on src/test/java/helpers/WaitUtils.java
> +    public void waitForWindowNumber(int numberOfWindows) {
same

2021-01-25 10:17 UTC, OleksandrMishchenkoGit commented on src/test/java/tests/SearchResultTests.java
> +        assertEquals(pageWithLocators.productTitle.getText(), "«" + SEARCH_WORD_PHONE + "»");
very weird test

2021-01-25 11:00 UTC, VladFedash commented on src/test/java/helpers/BaseOperations.java
> +        waitForElementVisibilityShort(driver.findElement(by));
Changed

2021-01-26 11:31 UTC, OleksandrMishchenkoGit approved these changes

2021-01-26 11:36 UTC, merged